name: Deploy

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  setup_ssh:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add known hosts
      run: |
        ssh-keyscan 20.157.92.44 >> ~/.ssh/known_hosts

  copy_files:
    runs-on: ubuntu-latest
    needs: setup_ssh
    steps:
    - name: Copy files using SCP
      run: |
        scp -o StrictHostKeyChecking=no -r ./target/* azureuser@20.157.92.44:/home/azureuser/MyShop
