name: Deploy

on:
  push:
    branches:
      - main

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  sync:
    runs-on: ubuntu-latest
    needs: start  # This job depends on the successful completion of the start job

    steps:
    - name: Sync files using rsync
      run: |
        rsync -avz \
          --exclude='venv/' \
          --exclude='.ignore' \
          -e 'ssh -o StrictHostKeyChecking=no' \
          ./ azureuser@20.157.92.44:/home/azureuser/MyShop

  end:
    runs-on: ubuntu-latest
    needs: sync  # This job depends on the successful completion of the sync job

    steps:
    - name: Notify deployment completion
      run: echo "Deployment completed successfully!"
